# Generated by Django 4.2.27 on 2026-02-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexam',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userexam',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexam',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexam',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexam',
            name='remaining_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexam',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
