# Generated by Django 4.2.27 on 2026-02-12 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team3', '0002_userexam_answers_userexam_is_paused_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexam',
            name='answers',
        ),
    ]
